openapi: 3.0.3
info:
  title: Acme Product Catalog API
  version: 0.0.1
paths: {}
components:
  schemas:
    Error:
      title: Error Response
      description: >-
        A JSON:API-compliant error response. This object is inherited by the specific
        response type.
      type: object
      required:
        - errors
      properties:
        errors:
          description: An array of Error objects
          type: array
          minItems: 1
          items:
            description: A JSON:API-compliant error object.
            type: object
            additionalProperties: false
            required:
              - status
              - title
            properties:
              id:
                description: a unique identifier for this particular occurrence of the problem
                type: string
                format: uuid
              links:
                description: >-
                  a link to further details about this particular occurrence of the
                  problem
                type: object
                nullable: true
                properties:
                  about:
                    $ref: './Link.yaml#/components/schemas/Link'
              status:
                description: the HTTP status code applicable to this problem
                type: integer
              code:
                description: an application-specific error code
                type: string
                maxLength: 10
              title:
                description: >-
                  a short, human-readable summary of the problem that SHOULD NOT
                  change from occurrence to occurrence of the problem, except for
                  purposes of localization
                type: string
                maxLength: 100
              detail:
                description: >-
                  a human-readable explanation specific to this occurrence of the
                  problem. Like title, this field’s value can be localized
                type: string
                maxLength: 150
              source:
                description: contains references to the source of the error
                type: object
                nullable: true
                properties:
                  pointer:
                    description: >-
                      a JSON Pointer [RFC6901] to the associated entity in the request
                      document
                    type: string
                    maxLength: 500
                  parameter:
                    description: indicates which URI query parameter caused the error
                    type: string
                    maxLength: 50
              meta:
                description: >-
                  a JSON meta object with non-standard meta-information about the
                  error
                type: object
                nullable: true
