openapi: 3.0.3
info:
  title: Acme Product Catalog API
  version: 0.0.1
paths: {}
components:
  parameters:
    productId:
      name: id
      in: path
      description: Product identifier
      required: true
      style: simple
      schema:
        type: string
        format: uuid
        example: 'd8ec6b7c-a5f9-16ac-76d0-7da97292c582'
