
networks:
  kong-net:
    name: kong-net
    external: false


services:
  kong-database:
    image: postgres:13.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: konguser
      POSTGRES_DB: kongdb
      POSTGRES_PASSWORD: kongpassword
    networks:
      - kong-net
  kong-migrations:
    image: kong:latest
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kongpassword
      KONG_PG_USER: konguser
      KONG_PG_DATABASE: kongdb
    networks:
      - kong-net
  apicurio-registry:
    image: apicurio/apicurio-registry-mem:2.4.4.Final
    ports:
      - 9090:8080
    networks:
      - kong-net
  kong-gateway:
    image: kong:latest
    depends_on:
      - kong-migrations
      - kong-database
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kongpassword
      KONG_PG_USER: konguser
      KONG_PG_DATABASE: kongdb
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    networks:
      - kong-net
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10



