apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-api
  name: productsapi-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: product-api